### PR TITLE
Add http-relative-path, remove https-stric

### PR DESCRIPTION
**Pull request by captnbp**
**Description of the change**

- To help migrate to the new version of Keycloak, `http-relative-path` helps to set /auth to avoid to break older setups (https://www.keycloak.org/migration/migrating-to-quarkus#_default_context_path_changed)
- The image scripts refer to `https-stric` parametter. This parametter doesn't exist in Keycloak doc, even with a good typo

**Benefits**

- `KEYCLOAK_HTTP_RELATIVE_PATH` will help users to set the old path `/auth` to migrate from older version
- `https-stric` has to be removed to avoid confusion

**Possible drawbacks**

None

**Applicable issues**

- #84

**Additional information**

None

### CODE REVIEW

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the delay, could you fix the conflicts ?

**Comment by captnbp** [comment]
> Hi, Sorry for the delay, could you fix the conflicts ?

Done !

**Comment by captnbp** [comment]
> Hi, I am sorry, there is also a conflict in `README.md`

Ok, just fixed @rafariossaa

**Comment by captnbp** [comment]
> Sorry, could you rebase your changes ? It seems another PR got in the middle.

Juste rebased

**Comment by bobertrublik** [comment]
Is this going to be added in 18.0.1? My setup is broken without the URL being at /auth :)

**Comment by FraPazGal** [comment]
Hello @bobertrublik,

This fix should be released in the public registries during the day after our internal CI finishes. After that, the chart will also get the updated container shortly.

**Comment by bobertrublik** [comment]
@FraPazGal Great thank you very much!

**Pull request merged**
