### PR TITLE
Feature/cache stack

### PR DESCRIPTION
**Pull request by jack1902**
**Description of the change**

Ensure that `cache-stack` is implemented via the env-vars present. If using `kubernetes` as the cache-stack, ensure additional settings are passed to fail fast.

**Benefits**

Previously, you could only set the cache-type, but `ispn` has various cache-stack mechanisms, which previously were ignored. I use this image via the keycloak helm-chart which requires some extra settings to ensure `kubernetes` as the cache-stack work.

**Possible drawbacks**

Only one I could see what that `CACHE_STACK` was previously defaulting to empty, so I have now updated it to the default `udp` cache-stack that keycloak would default too.

**Applicable issues**

closes: https://github.com/bitnami/bitnami-docker-keycloak/issues/69
relates to: https://github.com/bitnami/charts/issues/10236

**Additional information**

I will update `18` as well but want to agree on this approach first. Please DO NOT merge without 18 having the same treatment as 17

### CODE REVIEW

**Comment by jack1902** [comment]
i'm going to open a seperate issue around migration from KEYCLOAK_* to KC_* since I feel there should be standard on using KC_* over KEYCLOAK as the older KEYCLOAK vars don't "work" as previously intended

**Comment by jack1902** [comment]
@javsalgar I've raised this PR to address the initial issue, but have raised one for a larger discussion about removing `KEYCLOAK` for `KC` entirely which will reduce complexity

**Comment by marrws** [comment]
This a duplicate of the already merged #65

**Comment by jack1902** [comment]
Will close this, merging has clearly gone wrong upstream

**Pull request closed without merging**
