### PR TITLE
Use KC_HOSTNAME instead of FRONTEND_URL

### PR DESCRIPTION
**Pull request by jack1902**
**Description of the change**

Keycloak 17+ uses `KC_HOSTNAME` instead of the older `KEYCLOAK_FRONTEND_URL` this fixes that.

**Benefits**

new KC_HOSTNAME is actually used which is visible from the Quarkus logs under `frontendUrl`. This PR ensures that older implementations that use `KEYCLOAK_FRONTEND_URL` continue to function. That could be removed as it increases complexity.

**Possible drawbacks**

Increased complexity by keeping an old env-var around, namely `KEYCLOAK_FRONTEND_URL`

**Applicable issues**

closes: #59

**Additional information**

image

Source: https://www.keycloak.org/server/all-config?q=hostname

### CODE REVIEW

**Review by alemorcuq — COMMENTED** [review]
Thanks @jack1902 ! Could you please add a validation warning like this one (https://github.com/bitnami/bitnami-docker-phpmyadmin/blob/9c7553248bca86750c2b8a26a36e4dfdf3c36769/5/debian-10/rootfs/opt/bitnami/scripts/libphpmyadmin.sh#L42) to this image?

**Comment by jack1902** [comment]
@alemorcuq i've added it to the `validate` function, as I forsee it being extended quite a bit to shift people away from the old `KEYCLOAK_` pieces which don't correlate to anything compared to `KC_`

**Review by alemorcuq — APPROVED** [review]
Thank you very much!

**Comment by alemorcuq** [comment]
A new container should be released soon. Thanks!

**Pull request merged**
