### PR TITLE
Add support for MySQL and MariaDB

### PR DESCRIPTION
**Pull request by jachinte**
**Description of the change**

This PR adds support for MySQL and MariaDB. As suggested in #4, I use `mysql-client` from [`bitnami-docker-wordpress`](https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/Dockerfile#L15). I also created a new module (`com.mysql`) so that Keycloak can use the MySQL Connector library, and added one additional environment variable (`KEYCLOAK_DATABASE_VENDOR`).

I tested the changes using both MySQL and MariaDB; the sample `docker-compose.*.yml` files are included in the changes.

**Benefits**

The container can now be used with MySQL and MariaDB.

**Possible drawbacks**

I am not aware of any drawback.

**Applicable issues**

#4

**Additional information**

Is [`Dockerfile#L21`](https://github.com/jachinte/bitnami-docker-keycloak/blob/master/15/debian-10/Dockerfile#L21) a good place to create the MySQL module? I tried doing it from `libkeycloak.sh` but I got permission denied errors when creating the new directories and files.

### CODE REVIEW

**Comment by rafariossaa** [comment]
Hi,
  Thanks for this PR, we can not merge it directly because we have to add things in our internal pipeline in order to include the database connector in the container.
  For this I am creating a internal task, we will come back as soon as possible.

**Comment by scydas** [comment]
Hi @rafariossaa @jachinte ,
This is a very good feature and I need it. It's been 5 months, when will this pr be merged? thanks!

**Comment by rafariossaa** [comment]
Hi,
  Sorry, no news so far.
  In any case, if it happens you would like to send a PR to add this feature we will be glad to review and merge it.

**Comment by rafariossaa** [comment]
Hi,
  I this still in our backlog, I am sorry but I can not provide an ETA.

**Comment by javsalgar** [comment]
Hi,

I will forward this to the engineering team to see if we can re-prioritize.

**Comment by optimus-kart** [comment]
Any updates  on this ?

**Comment by rafariossaa** [comment]
Hi, there are several conflicts that should be fixed. Could you take a look to them ?

**Comment by carrodher** [comment]
Thanks for the PR, unfortunately, there are several changes to be performed in our internal tooling and our test & release pipeline in order to integrate a new component as part of this container.
Due to our capacity and other priorities the team has, we won't be able to do this effort in the mid-term.

**Comment by leoandrea7** [comment]
@carrodher This is very serious....

**Pull request closed without merging**
